# Generated by Django 4.1.5 on 2023-02-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
